Fix it to return non-zero exit code when a command failed due to validation error
Example:

```
$ variant foo
variant ≫ starting task foo
foo!
Z-MAC-C-036:github-actions c-ykuoka$ cat Variantfile
parameters:
- name: event
  type: object
  default: "/github/workflow/event.json"
script: |
  cat <<EOF
  {{ get "event" | toYaml }}
  EOF

tasks:
  foo:
    script: |
      echo foo!
```

BEFORE:
```
$ variant0350 fo
variant0350. ≫ one or more inputs are not valid in vars:
map[args:[fo] cmd:variant0350 env:dev event:fo]:
variant0350. ≫ one or more inputs are not valid in varsDumo:
{
  "args": [
    "fo"
  ],
  "cmd": "variant0350",
  "env": "dev",
  "event": "fo"
}:
variant0350. ≫ one or more inputs are not valid in kv:
{
  "args": [
    "fo"
  ],
  "cmd": "variant0350",
  "env": "dev",
  "event": "fo"
}:
variant0350. ≫ - event: Invalid type. Expected: object, given: string

$ echo $?
0
```

AFTER:
```
$ variant fo
Error: argument "event" of task "variant" is invali
Caused by: event: Invalid type. Expected: object, given: string

$ echo $?
1
```